### ISSUE TITLE
Consider making this crate a wrapper of libc functions?

### ISSUE THREAD

**Issue by upsuper** [dcuddeback/termios-rs#14]
It seems to me that all FFI functions, and most, if not all, constants defined in this crate have already been defined in libc, and libc has a much wider platform support. But this crate is still a useful wrapper on top of the raw FFI functions. So I wonder whether it makes sense to just make this crate a wrapper of libc to provide the slightly higher level abstraction.

The reason I'm raising this is because I want to make my application support musl, but it uses `console` crate which depends on this crate. Then I downloaded this crate and do the following modification:
* replace `ffi::` and `::os::target::` with `libc::` in `lib.rs`
* remove `mod ffi;`
* make `Termios` not implement `Debug`, `Eq`, and `PartialEq`

and make cargo use the modified version to replace the dependency. At the end, everything seems to work just fine. The result execution is statically linked, and it works (although not perfectly).

I was also thinking about submitting a PR to `console` crate to drop this dependency and use `libc` directly, but after I investigated the usage in that crate, it seems to me that this crate does provide a reasonable wrapper over the raw functions. And thus this issue.

As far as I can see, the only two problems of making it a wrapper of libc would be
* It may need some effort to import constants to their corresponding mods.
* `Termios` would become not `Debug`, `Eq`, or `PartialEq`, which would be a breaking change.

What do you think about this?

**Comment by upsuper** [comment]
I also tried to port support of musl from libc to this crate, but it seems that libc makes use of some unstable Rust feature, which is not usable elsewhere, and thus porting that doesn't seem to be easy either.

**Comment by dcuddeback** [comment]
@upsuper First of all, thank you for opening an issue to discuss the idea before submitting a PR. That makes my life as a maintainer much easier. :)

This is something I've thought about, but I haven't looked into it much more than thinking that it's a possibility.

> have already been defined in libc

Actually, the reason this library exists at all is that the termios definitions didn't exist in early versions of libc (v0.1), which is when I created this library, which I needed in order to implement the `serial` library. I recall reading at the time that the goal of the libc crate was to only provide definitions that exist across all supported platforms. Hence, early versions of libc didn't provide platform-specific definitions like the termios API. If that had existed in libc at the time, it's possible that I may have never created this crate.

> make `Termios` not implement `Debug`, `Eq`, and `PartialEq`

That would be a breaking change. What's the harm in having those traits implemented? This also seems orthogonal to whether or not it wraps the libc definitions. 

> and it works (although not perfectly)

What issues made it less than perfect?

> drop this dependency and use `libc` directly, but ... seems to me that this crate does provide a reasonable wrapper

I'm considering doing the same for `serial`, but haven't looked into doing it yet. What value does this crate add over using `libc` directly that made you reconsider?

**Comment by dcuddeback** [comment]
@upsuper Oops. I submitted that last comment by mistake when waking up my screensaver. I had a little more to say that I was still editing in:

As I mentioned in the last comment, I've considered making this crate a wrapper for `libc` and I've also considered dropping it as a dependency in my own crates and using `libc` directly. Since it sounds like you've looked at both, my questions in my previous comment are aimed at trying to uncover any trade-offs to help me decide how to go forward.

Regarding dropping the impls for `Termios`, is that necessary in order to wrap the `libc` definition?

> I also tried to port support of musl from libc to this crate, but it seems that libc makes use of some unstable Rust feature, which is not usable elsewhere, and thus porting that doesn't seem to be easy either.

By port musl support from `libc`, are you referring to copying the definitions into this crate rather than referring to the `libc` definitions from this crate? I assume that's what you mean, but want to be sure.

**Comment by upsuper** [comment]
Sorry for the delay.

> That would be a breaking change. What's the harm in having those traits implemented? This also seems orthogonal to whether or not it wraps the libc definitions.

Yeah, that's a breaking change. There is no harm, but it is basically just impossible unless you want to manually implement those trait for all the platforms, since those structs in `libc` don't derive them. So it's not orthogonal.

> What issues made it less than perfect?

I basically use `console` crate to clear the line I printed, but in the musl version, it doesn't work (while the gnu build with unmodified `termios` seems to work). I have no idea why and I haven't got time to investigate that.

> I'm considering doing the same for serial, but haven't looked into doing it yet. What value does this crate add over using `libc` directly that made you reconsider?

From brief read of code of the `console` crate, I thought the safe API of `Termios` is an elegant wrapper for all the termios stuff. Reading the code a bit further, it seems that the constructor `from_fd` would still need an `unsafe` block to get the file descriptor, which probably weakens the point.

> Regarding dropping the impls for Termios, is that necessary in order to wrap the libc definition?

I'm not asking for dropping impls for `Termios` struct... I'm thinking about dropping the constants. That's probably not necessary, but basically I see no reason to independently maintain a duplicate set of those constants.

> By port musl support from `libc`, are you referring to copying the definitions into this crate rather than referring to the `libc` definitions from this crate? I assume that's what you mean, but want to be sure.

I was trying to copy part of the `cfg_if! { }` block for the `#[link]` attribute on `extern { }` into `ffi.rs`.

**Comment by upsuper** [comment]
As a recording, I got an email from @Susurrus regarding this issue two days ago:
> For some reason I'm unable to comment on issue #14 in your repo, David, nor can I create a new issue, so I thought I'd follow up over email.
> 
> I wanted to point out that I implemented the safe wrapper for the termios API in (nix) [https://github.com/nix-rust/nix] which was released in the last version, 0.9.0. I actually use it in one of my crates. I thought this would be helpful for the discussion.

**Comment by dcuddeback** [comment]
> since those structs in `libc` don't derive them

Ah, thanks. That answers my question.

> I haven't got time to investigate that.

No problem. Thanks for taking the time to share the results of your investigation to date.

> I'm not asking for dropping impls for `Termios` struct

That's not what I was implying. That was a continuation of my earlier question about it being a breaking change. You answer about `libc` not deriving them covers this question, too.

> `cfg_if! { }` block for the `#[link]` attribute on `extern { }`

I see, thank you. I'll look out for that when I look into doing this.

It will be a while until I look at this. I've been burned out on open-source lately and I'm looking at alternatives to GitHub to move my projects to so that I can enjoy my projects again.

P.S. There's no need to relay messages from blocked users. They're blocked for a reason. ;)

**Comment by dcuddeback** [comment]
@upsuper Looking at this again, I saw you wrote this:

> The reason I'm raising this is because I want to make my application support musl

I think that detail got buried in all the discussion about wrapping libc before. What's the issue with termios on musl?

I'm leaning toward "no" on wrapping libc, because I think it's not worth the work. But I noticed your issue is really about supporting musl, which is much more important to me.

**Comment by upsuper** [comment]
Ah, sorry, it has been too long since this issue was opened.

I just tried the program I think I had problem with, but it seems to work just fine without the extra patching, and I'm not sure what the problem was.

We can probably close this issue.
