### ISSUE TITLE
Relicense under dual MIT/Apache-2.0

### ISSUE THREAD

**Issue by cmr** [dcuddeback/termios-rs#4]
This issue was automatically generated. Feel free to close without ceremony if
you do not agree with re-licensing or if it is not possible for other reasons.
Respond to @cmr with any questions or concerns, or pop over to
`#rust-offtopic` on IRC to discuss.

You're receiving this because someone (perhaps the project maintainer)
published a crates.io package with the license as "MIT" xor "Apache-2.0" and
the repository field pointing here.

TL;DR the Rust ecosystem is largely Apache-2.0. Being available under that
license is good for interoperation. The MIT license as an add-on can be nice
for GPLv2 projects to use your code.

# Why?

The MIT license requires reproducing countless copies of the same copyright
header with different names in the copyright field, for every MIT library in
use. The Apache license does not have this drawback. However, this is not the
primary motivation for me creating these issues. The Apache license also has
protections from patent trolls and an explicit contribution licensing clause.
However, the Apache license is incompatible with GPLv2. This is why Rust is
dual-licensed as MIT/Apache (the "primary" license being Apache, MIT only for
GPLv2 compat), and doing so would be wise for this project. This also makes
this crate suitable for inclusion and unrestricted sharing in the Rust
standard distribution and other projects using dual MIT/Apache, such as my
personal ulterior motive, [the Robigalia project](https://robigalia.org).

Some ask, "Does this really apply to binary redistributions? Does MIT really
require reproducing the whole thing?" I'm not a lawyer, and I can't give legal
advice, but some Google Android apps include open source attributions using
this interpretation. [Others also agree with
it](https://www.quora.com/Does-the-MIT-license-require-attribution-in-a-binary-only-distribution).
But, again, the copyright notice redistribution is not the primary motivation
for the dual-licensing. It's stronger protections to licensees and better
interoperation with the wider Rust ecosystem.

# How?

To do this, get explicit approval from each contributor of copyrightable work
(as not all contributions qualify for copyright, due to not being a "creative
work", e.g. a typo fix) and then add the following to your README:

```
## License

Licensed under either of

 * Apache License, Version 2.0, ([LICENSE-APACHE](LICENSE-APACHE) or http://www.apache.org/licenses/LICENSE-2.0)
 * MIT license ([LICENSE-MIT](LICENSE-MIT) or http://opensource.org/licenses/MIT)

at your option.

### Contribution

Unless you explicitly state otherwise, any contribution intentionally submitted
for inclusion in the work by you, as defined in the Apache-2.0 license, shall be dual licensed as above, without any
additional terms or conditions.
```

and in your license headers, if you have them, use the following boilerplate
(based on that used in Rust):

```
// Copyright 2016 termios-rs Developers
//
// Licensed under the Apache License, Version 2.0, <LICENSE-APACHE or
// http://apache.org/licenses/LICENSE-2.0> or the MIT license <LICENSE-MIT or
// http://opensource.org/licenses/MIT>, at your option. This file may not be
// copied, modified, or distributed except according to those terms.
```

It's commonly asked whether license headers are required. I'm not comfortable
making an official recommendation either way, but the Apache license
recommends it in their appendix on how to use the license.

Be sure to add the relevant `LICENSE-{MIT,APACHE}` files. You can copy these
from the [Rust](https://github.com/rust-lang/rust) repo for a plain-text
version.

And don't forget to update the `license` metadata in your `Cargo.toml` to:

    license = "MIT OR Apache-2.0"

I'll be going through projects which agree to be relicensed and have approval
by the necessary contributors and doing this changes, so feel free to leave
the heavy lifting to me!

# Contributor checkoff

To agree to relicensing, comment with :

    I license past and future contributions under the dual MIT/Apache-2.0 license, allowing licensees to chose either at their option.

Or, if you're a contributor, you can check the box in this repo next to your
name. My scripts will pick this exact phrase up and check your checkbox, but
I'll come through and manually review this issue later as well.

 - [x] @dcuddeback
 - [x] @conradkleinespel
 - [x] @myfreeweb

**Comment by dcuddeback** [comment]
@conradkleinespel @myfreeweb @qbit: Do you agree to relicense under dual MIT/Apache-2.0 license?

**Comment by conradkleinespel** [comment]
I license past and future contributions under the dual MIT/Apache-2.0 license, allowing licensees to chose either at their option.

**Comment by conradkleinespel** [comment]
@dcuddeback I'm all for it.

Side notes:

- `termios-rs` does not currently comply with the issue of "different names in the copyright field", so re-licensing for **this** reason makes little sense.
- MIT is both Apache-compatible and GPL-compatible, which means we can already work with it in a large variety of ecosystems.
- Apache 2.0 has protection against patent-trolls, that is good. But if you want to enforce this, you'll have to ask every contributor to release the code under both MIT *and* Apache 2.0. Right?

**Comment by myfreeweb** [comment]
I license past and future contributions under the dual MIT/Apache-2.0 license, allowing licensees to chose either at their option.

**Comment by conradkleinespel** [comment]
I license past and future contributions under the dual MIT/Apache-2.0 license, allowing licensees to chose either at their option.

**Comment by qbit** [comment]
I license past and future contributions under the dual MIT/Apache-2.0 license, allowing licensees to chose either at their option.

**Comment by dcuddeback** [comment]
@conradkleinespel Thanks for providing some perspective. I find licensing issues to be confusing at times, so it's helpful to get a second opinion. I actually have some questions about the points that you raised, if you don't mind. I haven't made up my mind yet whether relicensing has any advantages, so I'd love to hear your thoughts.

* Could you elaborate on how `termios-rs` doesn't comply with the issue of "different names in the copyright field?" My understanding of this issue was that the MIT license requires dependent projects to credit their MIT-licensed dependencies, so that would affect projects that depend on `termios-rs`, not `termios-rs` directly.
* The main advantage that I see to interop is for people that are concerned about patent protection.
* By licensing under MIT and Apache-2.0, do you mean that I would have to require users to accept both licenses simultaneously instead of choosing one? Since the MIT license doesn't grant patent licenses, I figured that it can't be used as a loophole around the litigation clause in the Apache license. It's probably not that important for a small wrapper library like `termios-rs`. I just want to make sure I'm not overlooking something.

**Comment by conradkleinespel** [comment]
@dcuddeback Sure ! I'm not a lawyer, so anything I say here must be taken with a grain of salt.

- At the moment, you say in the `LICENSE` file, `Copyright © 2015 David Cuddeback`. This means you don't comply with the issue of "different names in the copyright field". It should, in theory, list all of the contributors, because, by law, every contributor retains the copyright to the code they've contributed, I think.
- Ah yes, OK. That makes sense to me now.
- The Apache 2.0 license specifies that any contributions to the project are made under the terms of the Apache 2.0 license. But MIT says no such thing. So any code contributed by anyone to the project would, in theory, not be available legally under the terms of the MIT license. That means that by introducing the Apache 2.0 license, things get a bit weird IMO.

In fact, I would be in favor of simply re-licensing the project as Apache 2.0 only, because I think this license is both permissive and protective. Given that contributors have already given you their consent to license their contributions as Apache 2.0, that would, IMO, be the best and easiest option. But who am I to decide what you do with the library you created in the first place :smiley:

**Comment by qbit** [comment]
> Given that contributors have already given you their consent to license their contributions as Apache 2.0, that would, IMO, be the best and easiest option. 

I gave consent to re-license as MIT/Apache-2.0. There was nothing said about only single licensing as Apache-2.0. Legally, I don't think you would be able to take the statement `I license past and future contributions under the dual MIT/Apache-2.0 license, allowing licensees to chose either at their option.` and argue that you can apply ONLY Apache-2.0.

**Comment by conradkleinespel** [comment]
@qbit You gave consent that we could chose either *at our option*. Re-licensing your work as only Apache 2.0 is legal, I believe. My option is to chose Apache 2.0 anyway.

**Comment by qbit** [comment]
Right, I miss understood the last bit.

**Comment by dcuddeback** [comment]
@conradkleinespel Thanks for explaining.

Regarding the `LICENSE` file, I don't think that's what was meant by "the MIT license requires reproducing countless copies of the same copyright header with different names in the copyright field, for every MIT library in use." I think he's referring to this statement from the MIT license:

> The above copyright notice and this permission notice shall be
> included in all copies or substantial portions of the Software.

I think he meant to say that other projects must include the copyright and license of each of its MIT-licensed dependencies. I don't think that's actually true, though. To your point, contributors do retain the copyright on their contributions. I've seen many projects use an `AUTHORS` file to document who has copyright of parts of the code. To my knowledge, that doesn't change the fact of who has copyright. It's just documentation. I've been keeping a similar list in the README.

Regarding the contributions clause of the Apache license, I think the original comment tried to address that by suggesting adding a similar clause to the README. However, the README doesn't seem as legally binding as a license, so I'm not if that that solution is reliable. I agree with you that it makes things weird.

**Comment by dcuddeback** [comment]
I think this project should stick with the MIT license for now.
There's always the option of dual-licensing in the future, but for now, I don't see enough of a benefit.
My reasons are detailed below.
Sorry everyone for bugging you for your consent only to change my mind.

I want all of my projects to be simple to use, including easy-to-understand licensing terms.
The MIT license fits the bill nicely.
Some of the issues raised in this thread show that dual-licensing can be tricky.
After analyzing the potential benefits (see below), they seem to be very minor for this project.
The risk of unforseen consequences of dual-licensing seems to outweigh the potential benefits.
Given the small size and the nature of this project, I don't think it's worth spending more time analyzing the trade-offs of dual-licensing at this time.

This thread claims two benefits to the Apache 2 license:

1. Not needing to repeat the copyright notice for every MIT-licensed library in use.
2. Patent protection.

I believe that neither of these are significant benefits for this project.
This isn’t meant as a knock against the Apache 2 license.
It just means that it doesn’t seem benefitial in this context.

## Reproducing Copyright Notice

This issue claims that programs that use this project as a dependency would have to reproduce the license and copyright notices in their projects.
I don't agree with that interpretation of the MIT license, because it only applies to "copies" of the software.
I think common sense would not consider linking to another project as making a copy of the dependency.
Admittedly, Apache 2 is clearer about this by having an explicit exception for works that only link to the protected work.

## Patent Protection

In order to invoke the Apache 2 license's patent protection, at least three things must be true:

1. **The library must have at least one patent license available to revoke.**

    This is unlikely to ever be the case for this library.
    Patents protect functionality.
    The functionality of termios is implemented in system libraries, not in this project.
    This project just provides a wrapper for calling the system libraries.
    This project has no patents to grant licenses for and therefor nothing to revoke in retaliation to a lawsuit.

2. **The entity instigating patent litigation must be relying on the license granted to them by the Apache license.**

    This means that the entity filing the lawsuit must be using this library.
    Since patent trolls typically don't have any products of their own, they're unlikely to be using this library.


3. **The lawsuit must allege that _this_ project infringes on a patent.**

    Termios is defined by a POSIX standard, which is implemented in several ([over two dozen according to Wikipedia](https://en.wikipedia.org/wiki/POSIX#POSIX-oriented_operating_systems)) operating systems.
    If another entity wants to file a lawsuit to claim infringement based on termios functionality implemented in the system library, this project can't offer any protection.

Since this library can't offer patent protection, all that's left is offering the *appearance* of patent protection.
I don't think that's worth dual-licensing for, and could in fact be misleading.

GNU recommends Apache 2 over MIT for patent protection, but even they qualify their recommendation by saying "for substantial programs" (https://www.gnu.org/licenses/license-list#Expat).
I think the above analysis shows why: it takes a substantial project for the protection to be effective.

**Comment by conradkleinespel** [comment]
@dcuddeback Sounds good ! :+1:

**Comment by qbit** [comment]
Sweet! Simplicity FTW! :+1:

**Comment by dcuddeback** [comment]
Thanks guys.
